ackermann_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : input_mux/drive
        timeout : 0.2
        priority: 10
      joystick:
        topic   : input_mux/joy
        timeout : 0.2
        priority: 100